baseURL = 'https://antimaterie.ro/'
title = 'Antimaterie'
theme = "zen"
languageCode = "ro-RO"

[params]
alpine = false
blogSections = [ "blog", "post" ]
breadcrumbSections = [ "section2", "section3" ]
cookieConsent = true
contact = "info@example.org"
copyright = "This site is licensed under a  [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)."
dateformat = "January 2, 2006"
description = ""
favicon = ""
feedlinks = true
footer = "We are not Borg"
icon = ""
image = ""
imageMaxWidth = "400"
internalPagination = false
jquery = false
languageDir = "ltr"
logo = false
mainSections = [ "flux", "distilat" ]
math = false
menuInHeader = true
microUsername = ""
mobileMenu = true
mobileMenuOutline = true
piwikTrackerUrl = ""
plausibleSiteID = "1"
plausibleTrackerURL = ""
poweredby = true
privacyPolicyUrl = ""
relatedposts = true
sassTranspiler = "dartsass"
searchLimit = 20
sidebar = true
siteName = false
submitted = true
umbrella = true

  [params.author]

  [params.podcast]
  explicit = "false/true"
  block = "no/yes"
  complete = "no/yes"
  type = "episodic/serial"
  local = false
  preload = "none/metadata/auto"

    [params.podcast.category]
    subcategories = [ ]

    [params.podcast.owner]
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
